image: "python:3.7" 
before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - test

test:
  stage: test
  script:
    - echo "Starting Automated Unit Tests"
    - python3 -m unittest -b
